<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.1.4" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="11.1.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Metallic.Mvvm\Metallic.Mvvm.csproj" />
  </ItemGroup>
</Project>
