<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.3" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="11.2.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Metallic.Mvvm\Metallic.Mvvm.csproj" />
  </ItemGroup>
</Project>
